import { DataClassification } from './types'

export const mockDataClassifications: DataClassification[] = [
  {
    id: 'doc-1',
    title: 'Q3 Marketing Plan',
    from: 'Marketing Team',
    timestamp: '09:00 AM',
    fileType: 'PDF',
    fileSize: '1.2 MB',
    preview: 'Q3_Marketing_Plan.pdf\n\nThis document contains our quarterly marketing strategy, campaign timelines, and budget allocations for Q3 2026. It outlines our approach to promoting new product launches and market expansion in key regions.',
    sensitivityIndicators: [
      'Strategic business plans',
      'Budget information',
      'Market expansion data',
      'Product launch details',
    ],
    correctClassification: 'internal',
    shouldShareWith: 'External Marketing Agency',
  },
  {
    id: 'doc-2',
    title: 'Employee Handbook',
    from: 'Human Resources',
    timestamp: '08:15 AM',
    fileType: 'DOCX',
    fileSize: '2.5 MB',
    preview: 'Employee_Handbook_2026.docx\n\nCompany policies, code of conduct, benefits information, vacation policies, and general employee guidelines. This document is distributed to all employees on their first day.',
    sensitivityIndicators: [
      'Company policies',
      'Employee guidelines',
      'Publicly distributed document',
    ],
    correctClassification: 'internal',
    shouldShareWith: 'All Employees',
  },
  {
    id: 'doc-3',
    title: 'Customer Database Export',
    from: 'Database Admin',
    timestamp: '07:45 AM',
    fileType: 'CSV',
    fileSize: '45 MB',
    preview: 'customer_database_2026.csv\n\nContains customer names, email addresses, phone numbers, home addresses, purchase history, credit card last 4 digits, and customer lifetime value. Records for 50,000+ customers.',
    sensitivityIndicators: [
      'Personally Identifiable Information (PII)',
      'Customer names and contact information',
      'Customer financial data',
      'Email addresses and phone numbers',
      'Home addresses',
      'Purchase history',
    ],
    correctClassification: 'restricted',
    shouldShareWith: 'Authorized Data Team Members Only',
  },
  {
    id: 'doc-4',
    title: 'API Keys and Credentials',
    from: 'IT Security',
    timestamp: '10:30 AM',
    fileType: 'TXT',
    fileSize: '50 KB',
    preview: 'prod_api_keys_2026.txt\n\nProduction API keys, database passwords, SSH keys, OAuth tokens, and authentication credentials for all company services including AWS, Firebase, and third-party APIs.',
    sensitivityIndicators: [
      'Authentication credentials',
      'API keys and tokens',
      'Database passwords',
      'SSH keys',
      'Production system access',
      'OAuth credentials',
    ],
    correctClassification: 'restricted',
    shouldShareWith: 'System Administrators Only',
  },
  {
    id: 'doc-5',
    title: 'Blog Post: Company Culture',
    from: 'Communications',
    timestamp: '11:00 AM',
    fileType: 'DOCX',
    fileSize: '500 KB',
    preview: 'Blog_Company_Culture.docx\n\nArticle intended for public blog about company culture, team building events, and employee success stories. No sensitive information included. Ready for publication on company website.',
    sensitivityIndicators: [
      'Intended for external publication',
      'Public company information',
      'Employee testimonials (public)',
    ],
    correctClassification: 'public',
    shouldShareWith: 'Public Website',
  },
  {
    id: 'doc-6',
    title: 'Board Meeting Minutes',
    from: 'Executive Office',
    timestamp: '09:30 AM',
    fileType: 'DOCX',
    fileSize: '1.1 MB',
    preview: 'Board_Minutes_Q2_2026.docx\n\nMinutes from quarterly board meeting including financial results, strategic decisions, acquisition discussions, executive compensation, and investor relations updates. Contains forward-looking business strategy.',
    sensitivityIndicators: [
      'Strategic business plans',
      'Financial information',
      'Executive compensation',
      'Acquisition details',
      'Confidential contracts',
      'Board-level decisions',
    ],
    correctClassification: 'confidential',
    shouldShareWith: 'Board Members and Senior Executives Only',
  },
  {
    id: 'doc-7',
    title: 'Product Roadmap 2026',
    from: 'Product Management',
    timestamp: '10:15 AM',
    fileType: 'PDF',
    fileSize: '2.8 MB',
    preview: 'Product_Roadmap_2026.pdf\n\nUpcoming product features, timeline for releases, competitive analysis, market positioning strategy, and feature priorities for the next 12 months. Contains unreleased product information.',
    sensitivityIndicators: [
      'Unreleased product features',
      'Competitive analysis',
      'Timeline for launches',
      'Strategic positioning',
      'Internal roadmap only',
    ],
    correctClassification: 'confidential',
    shouldShareWith: 'Product and Engineering Teams Only',
  },
  {
    id: 'doc-8',
    title: 'Public Press Release',
    from: 'Communications',
    timestamp: '11:00 AM',
    fileType: 'DOCX',
    fileSize: '150 KB',
    preview: 'Press_Release_New_Partnership.docx\n\nAnnouncement of new strategic partnership with major tech company. Information intended for public distribution and media outlets. Contains marketing talking points and quotes.',
    sensitivityIndicators: [
      'Prepared for public release',
      'No confidential information',
      'Marketing materials',
      'Media distribution ready',
    ],
    correctClassification: 'public',
    shouldShareWith: 'Public and Media',
  },
  {
    id: 'doc-9',
    title: 'Employee Salary Data',
    from: 'Finance',
    timestamp: '09:00 AM',
    fileType: 'XLSX',
    fileSize: '850 KB',
    preview: 'Salary_Data_2026.xlsx\n\nComplete employee salary information including base pay, bonuses, equity, and compensation history for all 500+ employees in the company.',
    sensitivityIndicators: [
      'Personal salary information',
      'Employee compensation details',
      'Bonus and equity data',
      'Highly confidential',
      'Restricted access required',
    ],
    correctClassification: 'restricted',
    shouldShareWith: 'Finance and HR Leadership Only',
  },
  {
    id: 'doc-10',
    title: 'Technical Training Manual',
    from: 'IT Training',
    timestamp: '08:45 AM',
    fileType: 'PDF',
    fileSize: '5.2 MB',
    preview: 'Technical_Training_Manual.pdf\n\nInternal technical training documentation for employees covering company systems, tools, and procedures. Shared with all employees during onboarding.',
    sensitivityIndicators: [
      'Internal systems documentation',
      'Distributed to all employees',
      'Training material',
      'No confidential customer data',
    ],
    correctClassification: 'internal',
    shouldShareWith: 'All Employees',
  },
]
